### PR TITLE
LPS-116762 User is not unsubscribed from Blogs portlet if leaves site through a user group

### PR DESCRIPTION
**Pull request by pei-jung**
Hi @MarcellGyopos 

I made quite some changes to the PR that you sent me earlier this week. Sorry it took a while for me to review. A few things to note:

1. I moved the model listener and test to the blogs modules to avoid adding dependencies to the user-groups module.
2. There's a new pattern for using the `DataGuard` annotations for tests. DataGuard makes sure to clean up all the added entities during the tests. I've refactored the test you wrote to apply DataGuard.
3. We don't need to add the blogs to the page to subscribe in the backend. So I removed the logic in the tests for simplicity.

Please look over my changes and make sure the fix still works, and let me know if you have any questions. If everything looks good, feel free to do a ci:forward to send the PR to Brian. Thanks!

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi @pei-jung ,

You made a lot of good changes that I thank, but at the same time you took out the point.
When I unsubscribed customers from the sites, I considered several things.

1. If the user is removed from a group but has another group that is also subscribed to the same site, I will not unsubscribe.
2. If the user is removed from a group but has a direct member to the site,  I will not unsubscribe.

In the meantime, I’ve taken into account that there can be many sites, and different groups can be subscribed to each.

**Comment by pei-jung** [comment]
Hi @MarcellGyopos,

I preserved your logic when I consolidated your code. The two points that you mentioned are covered in https://github.com/MarcellGyopos/liferay-portal/pull/9/commits/4468ecdefc84207e1c4ea4ab1505434b6b271640#diff-3f414fba735081ce95af54392b4c8186R78-R79. [GroupLocalService.getUserGroups](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/GroupLocalServiceImpl.java#L2124-L2140) returns all the groups the user is associated with. If inherit is set to true, it also includes all the groups the user is part of indirectly via organizations or user groups (see https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/GroupLocalServiceImpl.java#L4295-L4326). So I'm only unsubscribing the user from the sites that he's no longer a member of after leaving the user group.

I ran your tests to make sure all tests passed with my changes before I refactored the tests. All uses cases should be covered, but if I miss anything, please let me know. Thanks!

**Comment by pei-jung** [comment]
Also, I did a lot of renamings of your code because we want to clearly distinguish `user group` and `group`. `Group` is a generic term used in Liferay to refer to a lot of things. Organizations, user groups, and sites are different types of group. That's why we need to be very explicit in naming to avoid any confusion, since group is already confusing by itself. It gets more complicated in groups relationships...

**Comment by MarcellGyopos** [comment]
Wow, then sorry for my previous comment, I was wrong. How much easier it would have been if I knew these methods. 
I will retest them and forward to Brian.
Thank you:)

**Comment by MarcellGyopos** [comment]
ci:forward

**Comment by rgusztus** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez can you take a look at this? not sure why the tests never get started. I resent the PR to myself to re-trigger the tests. https://github.com/pei-jung/liferay-portal/pull/680

**Comment by yichenroy** [comment]
ci:reopen

Attempting to track where the PR may have been queued, will close once investigation is complete.

**Comment by yichenroy** [comment]
ci:close

**Comment by yichenroy** [comment]
Hi @MarcellGyopos, the Liferay organization membership needs to be set to `public` in order for the pull request tester to work.
See `Become a member` section of this [Grow article](https://grow.liferay.com/share/Pull+Request+Tester+for+Liferay+Developers)

Github's [documentation](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership) on publicizing/privatizing organization association.

Thanks!

cc @pei-jung @patriciajeanperez

**Pull request closed without merging**
